/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("idea")
    id("java")
    kotlin("jvm") version "2.1.0-RC"
    id("application")
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://jitpack.io")
        name = "jitpack"
    }
}

idea {
    module {
        isDownloadJavadoc = true
        isDownloadSources = true
    }
}

dependencies {
    implementation("com.formdev:flatlaf:3.5.2")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.3")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.11.3")
}

tasks.getByName<Test>("test") {
    useJUnitPlatform()
}

application {
    mainClass = "com.github.huymaster.App"
    applicationName = "HocDSA"
}

tasks {
    "jar" {
        finalizedBy("fatJar")
    }
}

kotlin {
    jvmToolchain(8)
}

task("fatJar", Jar::class) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName.set("HocDSA.jar")
    manifest {
        attributes["Main-Class"] = "com.github.huymaster.App"
    }
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
    with(tasks.jar.get() as CopySpec)
}

